const txtAnimation = document.querySelector('h1');

new Typewriter(txtAnimation, {
    deleteSpeed: 20
})

.changeDelay(120)
.typeString('Bonjour moi c\'est <span style="color: pink">Jeanne S.</span>,<br>')
.pauseFor(500)
.typeString('<strong> <span style="color: pink">I</span>ntégratrice web</strong>')
.pauseFor(1200)
.deleteChars(17)
.pauseFor(300)
.typeString('<strong> <span style="color: pink">D</span>éveloppeuse web</strong> <br>')
.pauseFor(300)
.typeString('mon environnement ?<br>')
.pauseFor(300)
.deleteChars(19)
.typeString('<span style="color: blue"> CSS</span> !')
.pauseFor(500)
.deleteChars(5)
.typeString('<span style="color: magenta"> SCSS/SASS</span> !')
.pauseFor(500)
.deleteChars(11)
.typeString('<span style="color: yellow"> JavaScript</span> !')
.pauseFor(500)
.deleteChars(12)
.typeString('<span style="color: orangered"> Git/GitHub</span> !')
.pauseFor(500)
.deleteChars(12)
.typeString('<span style="color: grey"> Responsive</span> !')
.pauseFor(500)
.deleteChars(12)
.typeString('<span style="color: grey"> SEO</span> !')
.pauseFor(500)
.deleteChars(5)
.typeString('<span style="color: black"> Contactez-moi</span> !')
.start()